// <auto-generated/>
namespace UI
{
    using BE.Entidades;
    using BLL;
    using DAL.Dao;
    using System;
    using System.Windows.Forms;

    public partial class Login : Form
    {
        private const string nombreForm = "Login";

        private log4net.ILog log;
        private IPrincipal PrincipalForm;
        private IUsuarioBLL usuarioBLL;
        private IFormControl formControl;
        private readonly IIdiomaBLL idiomaBLL;
        private readonly IDigitoVerificador digitoVerificador;
        private readonly ITraductor traductor;

        public Login(IIdiomaBLL idiomaBLL, IDigitoVerificador digitoVerificador, ITraductor traductor)
        {
            this.digitoVerificador = digitoVerificador;
            this.idiomaBLL = idiomaBLL;
            this.traductor = traductor;
            InitializeComponent();
            txt_contraseña.PasswordChar = '*';
        }
        
        private void Form1_Load(object sender, EventArgs e)
        {
            this.AcceptButton = btn_ingresar;
            log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
            PrincipalForm = IoCContainer.Resolve<IPrincipal>();
            usuarioBLL = IoCContainer.Resolve<IUsuarioBLL>();
            formControl = IoCContainer.Resolve<IFormControl>();
            CargarCombo();
            formControl.LenguajeSeleccionado = (Idioma)cbo_idioma.SelectedItem;
            Traduccir();
            ComprobarBaseDeDatos();
        }
        //COMPROBACION DE INTEGRIDAD
        //SI DIGITO VERIFICADOR ES DISTINTO AL ASIGNADO EN LA BASE ARROJA CARTEL DE PROBLEMA DE INTEGRIDAD.
        private void ComprobarBaseDeDatos()
        {
            if (!digitoVerificador.ComprobarIntegridad())
            {
                Alert.ShowSimpleAlert("Problema integridad base de datos, contacte al administrador", "MSJ000");

                this.Close();
            }
        }
        
        private void Traduccir()
        {
            traductor.Traduccir(this, nombreForm);
        }
        //IDIOMA
        private void CargarCombo()
        {
            var idioma = idiomaBLL.ObtenerTodosLosIdiomas();
            cbo_idioma.DataSource = idioma;
            cbo_idioma.ValueMember = "IdIdioma";
            cbo_idioma.DisplayMember = "Descripcion";
            cbo_idioma.SelectedIndex = 0;
        }
        //BOTON PARA LOGUEARSE
        private void btn_ingresar_Click(object sender, EventArgs e)
        {
            this.CatchException(() =>
            {
                var usuario = txt_user.Text;
                var contraseña = txt_contraseña.Text;
                ////lucas_matalima@hotmail.com pw: salom645

                if (usuarioBLL.ObtenerUsuarioConEmail(usuario).Activo)
                {
                    var ingresa = usuarioBLL.LogIn(usuario, contraseña);

                    if (ingresa)
                    {
                        this.Hide();
                        formControl.GuardarDatosSesionUsuario(usuarioBLL.ObtenerUsuarioConEmail(usuario));
                        PrincipalForm.ComprobarSiEsPrimerLogin(usuario);
                        PrincipalForm.Show();
                    }

                    else if (usuarioBLL.ObtenerUsuarioConEmail(usuario).ContadorIngresosIncorrectos < 3)
                    {
                        MessageBox.Show("Login Incorrecto","Ingresar al Sistema");
                    }
                    else
                    {
                        MessageBox.Show("Cuenta bloqueada contacte a su administrador","Ingresar al Sistema");
                    }
                }
                else
                {
                    MessageBox.Show("Coloque Usuario y Contraseña", "Ingresar al Sistema");
                }
            },
            (ex) => MessageBox.Show($"Ocurrio un error por lo siguiente {ex.Message}"));
        }
        //COMBOBOX PARA CAMBIAR DE IDIOMA
        private void cbo_idioma_SelectedIndexChanged(object sender, EventArgs e)
        {
            var lenguajeSeleccionado = (Idioma)cbo_idioma.SelectedItem;

            formControl.LenguajeSeleccionado = lenguajeSeleccionado;

            Traduccir();
        }
        //BOTON PARA SALIR DEL SISTEMA.
        private void btn_salir_Click(object sender, EventArgs e)
        {
           if (MessageBox.Show("¿Seguro que desea salir?", "Salir del Sistema", MessageBoxButtons.YesNo) == DialogResult.Yes)
           {
               this.Close();
            }
          
        }

        private void label1_Click(object sender, EventArgs e)
        {

        }

        private void txt_user_TextChanged(object sender, EventArgs e)
        {

        }
    }
}
