// <auto-generated/>
namespace UI
{
    partial class NegarPatUsuario
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.btnVolver = new System.Windows.Forms.Button();
            this.lblUsuario = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.PatHabilitadas = new System.Windows.Forms.ListBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.PatNegadas = new System.Windows.Forms.ListBox();
            this.btnHabilitar = new System.Windows.Forms.Button();
            this.btnNegar = new System.Windows.Forms.Button();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // btnVolver
            // 
            this.btnVolver.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.btnVolver.Location = new System.Drawing.Point(12, 7);
            this.btnVolver.Name = "btnVolver";
            this.btnVolver.Size = new System.Drawing.Size(69, 42);
            this.btnVolver.TabIndex = 62;
            this.btnVolver.Text = "VOLVER";
            this.btnVolver.UseVisualStyleBackColor = false;
            this.btnVolver.Click += new System.EventHandler(this.btnVolver_Click);
            // 
            // lblUsuario
            // 
            this.lblUsuario.AutoSize = true;
            this.lblUsuario.Location = new System.Drawing.Point(22, 52);
            this.lblUsuario.Name = "lblUsuario";
            this.lblUsuario.Size = new System.Drawing.Size(59, 13);
            this.lblUsuario.TabIndex = 61;
            this.lblUsuario.Text = "USUARIO:";
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.PatHabilitadas);
            this.groupBox1.Location = new System.Drawing.Point(12, 78);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(176, 200);
            this.groupBox1.TabIndex = 60;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Patentes Habilitadas";
            // 
            // PatHabilitadas
            // 
            this.PatHabilitadas.FormattingEnabled = true;
            this.PatHabilitadas.Location = new System.Drawing.Point(7, 19);
            this.PatHabilitadas.Name = "PatHabilitadas";
            this.PatHabilitadas.Size = new System.Drawing.Size(163, 173);
            this.PatHabilitadas.TabIndex = 0;
            this.PatHabilitadas.SelectedIndexChanged += new System.EventHandler(this.PatHabilitadas_SelectedIndexChanged);
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.PatNegadas);
            this.groupBox2.Location = new System.Drawing.Point(211, 78);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(176, 200);
            this.groupBox2.TabIndex = 61;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Patentes Negadas";
            // 
            // PatNegadas
            // 
            this.PatNegadas.FormattingEnabled = true;
            this.PatNegadas.Location = new System.Drawing.Point(6, 21);
            this.PatNegadas.Name = "PatNegadas";
            this.PatNegadas.Size = new System.Drawing.Size(163, 173);
            this.PatNegadas.TabIndex = 1;
            this.PatNegadas.SelectedIndexChanged += new System.EventHandler(this.PatNegadas_SelectedIndexChanged);
            // 
            // btnHabilitar
            // 
            this.btnHabilitar.Location = new System.Drawing.Point(252, 284);
            this.btnHabilitar.Name = "btnHabilitar";
            this.btnHabilitar.Size = new System.Drawing.Size(135, 43);
            this.btnHabilitar.TabIndex = 63;
            this.btnHabilitar.Text = "HABILITAR PATENTE";
            this.btnHabilitar.UseVisualStyleBackColor = true;
            this.btnHabilitar.Click += new System.EventHandler(this.btnHabilitar_Click);
            // 
            // btnNegar
            // 
            this.btnNegar.Location = new System.Drawing.Point(12, 284);
            this.btnNegar.Name = "btnNegar";
            this.btnNegar.Size = new System.Drawing.Size(135, 43);
            this.btnNegar.TabIndex = 64;
            this.btnNegar.Text = "NEGAR PATENTE";
            this.btnNegar.UseVisualStyleBackColor = true;
            this.btnNegar.Click += new System.EventHandler(this.btnNegar_Click);
            // 
            // NegarPatUsuario
            // 
            this.ClientSize = new System.Drawing.Size(391, 332);
            this.Controls.Add(this.btnNegar);
            this.Controls.Add(this.btnHabilitar);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.btnVolver);
            this.Controls.Add(this.lblUsuario);
            this.Controls.Add(this.groupBox1);
            this.Name = "NegarPatUsuario";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "ADMINISTRAR PATENTES";
            this.Load += new System.EventHandler(this.NegarPatUsuario_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.Button btnVolver;
        private System.Windows.Forms.Label lblUsuario;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Button btnHabilitar;
        private System.Windows.Forms.Button btnNegar;
        private System.Windows.Forms.ListBox PatHabilitadas;
        private System.Windows.Forms.ListBox PatNegadas;
    }
}