// <auto-generated/>
namespace UI
{
    partial class RestoreUI
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.lblStatus = new System.Windows.Forms.Label();
            this.lblProgreso = new System.Windows.Forms.Label();
            this.progressBar1 = new System.Windows.Forms.ProgressBar();
            this.txtBackFiles = new System.Windows.Forms.TextBox();
            this.btnExaminar = new System.Windows.Forms.Button();
            this.btnRestaurar = new System.Windows.Forms.Button();
            this.Label1 = new System.Windows.Forms.Label();
            this.btnVolver = new System.Windows.Forms.Button();
            this.opFile = new System.Windows.Forms.OpenFileDialog();
            this.SuspendLayout();
            // 
            // lblStatus
            // 
            this.lblStatus.AutoSize = true;
            this.lblStatus.Location = new System.Drawing.Point(6, 239);
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Size = new System.Drawing.Size(54, 13);
            this.lblStatus.TabIndex = 57;
            this.lblStatus.Text = "ESTADO:";
            // 
            // lblProgreso
            // 
            this.lblProgreso.AutoSize = true;
            this.lblProgreso.Location = new System.Drawing.Point(301, 241);
            this.lblProgreso.Name = "lblProgreso";
            this.lblProgreso.Size = new System.Drawing.Size(21, 13);
            this.lblProgreso.TabIndex = 56;
            this.lblProgreso.Text = "0%";
            // 
            // progressBar1
            // 
            this.progressBar1.Location = new System.Drawing.Point(60, 233);
            this.progressBar1.Margin = new System.Windows.Forms.Padding(2);
            this.progressBar1.Name = "progressBar1";
            this.progressBar1.Size = new System.Drawing.Size(240, 26);
            this.progressBar1.TabIndex = 55;
            // 
            // txtBackFiles
            // 
            this.txtBackFiles.Enabled = false;
            this.txtBackFiles.Location = new System.Drawing.Point(9, 127);
            this.txtBackFiles.Multiline = true;
            this.txtBackFiles.Name = "txtBackFiles";
            this.txtBackFiles.Size = new System.Drawing.Size(291, 95);
            this.txtBackFiles.TabIndex = 54;
            // 
            // btnExaminar
            // 
            this.btnExaminar.Location = new System.Drawing.Point(247, 90);
            this.btnExaminar.Name = "btnExaminar";
            this.btnExaminar.Size = new System.Drawing.Size(53, 21);
            this.btnExaminar.TabIndex = 53;
            this.btnExaminar.Text = "...";
            this.btnExaminar.UseVisualStyleBackColor = true;
            this.btnExaminar.Click += new System.EventHandler(this.btnExaminar_Click);
            // 
            // btnRestaurar
            // 
            this.btnRestaurar.Location = new System.Drawing.Point(125, 281);
            this.btnRestaurar.Name = "btnRestaurar";
            this.btnRestaurar.Size = new System.Drawing.Size(79, 31);
            this.btnRestaurar.TabIndex = 52;
            this.btnRestaurar.Text = "Restaurar";
            this.btnRestaurar.UseVisualStyleBackColor = true;
            this.btnRestaurar.Click += new System.EventHandler(this.btnRestaurar_Click);
            // 
            // Label1
            // 
            this.Label1.AutoSize = true;
            this.Label1.Location = new System.Drawing.Point(12, 93);
            this.Label1.Name = "Label1";
            this.Label1.Size = new System.Drawing.Size(197, 13);
            this.Label1.TabIndex = 50;
            this.Label1.Text = "SELECCIONE COPIA DE SEGURIDAD:";
            // 
            // btnVolver
            // 
            this.btnVolver.BackColor = System.Drawing.Color.Gray;
            this.btnVolver.Location = new System.Drawing.Point(125, 12);
            this.btnVolver.Name = "btnVolver";
            this.btnVolver.Size = new System.Drawing.Size(79, 51);
            this.btnVolver.TabIndex = 58;
            this.btnVolver.Text = "VOLVER";
            this.btnVolver.UseVisualStyleBackColor = false;
            this.btnVolver.Click += new System.EventHandler(this.btnVolver_Click);
            // 
            // opFile
            // 
            this.opFile.FileName = "openFileDialog1";
            this.opFile.Multiselect = true;
            // 
            // RestoreUI
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(321, 316);
            this.Controls.Add(this.btnVolver);
            this.Controls.Add(this.lblStatus);
            this.Controls.Add(this.lblProgreso);
            this.Controls.Add(this.progressBar1);
            this.Controls.Add(this.txtBackFiles);
            this.Controls.Add(this.btnExaminar);
            this.Controls.Add(this.btnRestaurar);
            this.Controls.Add(this.Label1);
            this.Name = "RestoreUI";
            this.Text = "RESTAURAR COPIA DE SEGURIDAD";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.RestoreUI_FormClosing);
            this.Load += new System.EventHandler(this.RestoreUI_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label lblStatus;
        private System.Windows.Forms.Label lblProgreso;
        private System.Windows.Forms.ProgressBar progressBar1;
        private System.Windows.Forms.TextBox txtBackFiles;
        internal System.Windows.Forms.Button btnExaminar;
        internal System.Windows.Forms.Button btnRestaurar;
        internal System.Windows.Forms.Label Label1;
        internal System.Windows.Forms.Button btnVolver;
        private System.Windows.Forms.OpenFileDialog opFile;
    }
}